version: "3"
services:
  java:
    container_name: java
    build:
      context: ./docker/java
    image: quickstart-java-maven
    volumes:
      - "./app:/app"
      - "~/.m2:/root/.m2"
    ports:
      - "8080:8080"